version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.17.0
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo removing the node_modules and src
      - rm -rf node_modules
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
